// Generates every app icon raster from the committed SVG source. Run it, do not hand place PNGs.
//
//   node scripts/app-icons.mjs           regenerate and report
//   node scripts/app-icons.mjs --check   fail if any output is missing or stale
//
// WHY A SCRIPT. Before this, iOS shipped no icon at all (AppIcon.appiconset held Contents.json and
// zero images, so the home screen drew the grey placeholder) and Android shipped the stock teal
// robot from the React Native template. Hand placed PNGs rot: a mark gets refined and nine files
// out of eleven get updated. The SVG in brand/icon is the source of truth and these are derived
// artifacts, regenerated by one command.
//
// THE SOURCES ARE DIFFERENT ART, NOT THE SAME ART AT TWO SIZES.
//  - icon-ios.svg is full bleed on a square canvas with ninety degree corners, because iOS applies
//    its own superellipse mask and a pre rounded source double masks into visible fringing.
//  - icon-android-foreground.svg is drawn small on a 108dp canvas so the mark clears the 66dp
//    circle Google guarantees is visible under every OEM mask, with the field supplied separately
//    by icon-android-background.svg so the launcher can parallax the two layers.
//
// The rasteriser is ImageMagick. Its SVG delegate prefers rsvg-convert and falls back to its own
// renderer when that is absent; both were checked against this artwork by rendering and looking at
// the result, and the geometry was measured rather than eyeballed (see verifyGeometry below).

import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {existsSync, mkdirSync, readFileSync, writeFileSync, rmSync} from 'node:fs';
import {dirname, join} from 'node:path';

const REPO = join(import.meta.dirname, '..');
const SRC = join(REPO, 'brand', 'icon');
const CHECK = process.argv.includes('--check');

const IOS_SRC = join(SRC, 'icon-ios.svg');
const AND_FG = join(SRC, 'icon-android-foreground.svg');
const AND_BG = join(SRC, 'icon-android-background.svg');

for (const f of [IOS_SRC, AND_FG, AND_BG]) {
  if (!existsSync(f)) {
    throw new Error(`icon source missing: ${f}. The rasters are derived; the SVG is the source.`);
  }
}

// The rasteriser is an external binary, so say so in a sentence rather than letting an ENOENT from
// deep inside a render surface as the error. This matters most in CI, where the failure would
// otherwise read as a broken icon rather than a missing tool.
try {
  execFileSync('magick', ['-version'], {stdio: 'ignore'});
} catch {
  console.error(
    'ImageMagick (magick) is not on PATH, so no icon can be rendered or checked.\n' +
      'Install it (brew install imagemagick) or, in CI, add it to the job before this step.',
  );
  process.exit(1);
}

// iOS. Every slot Contents.json declares, as pixel sizes. 120 and 40 each serve two slots (40@3x
// and 60@2x; 20@2x and 40@1x), and one file per pixel size is referenced twice rather than written
// twice, so there is exactly one 120px icon in the tree and not two that can disagree.
const IOS_SLOTS = [
  {size: '20x20', scale: '2x', px: 40},
  {size: '20x20', scale: '3x', px: 60},
  {size: '29x29', scale: '2x', px: 58},
  {size: '29x29', scale: '3x', px: 87},
  {size: '40x40', scale: '2x', px: 80},
  {size: '40x40', scale: '3x', px: 120},
  {size: '60x60', scale: '2x', px: 120},
  {size: '60x60', scale: '3x', px: 180},
];
const IOS_MARKETING = 1024;
const IOS_DIR = join(REPO, 'ios', 'GritChat', 'Images.xcassets', 'AppIcon.appiconset');

// Android. Legacy launchers get a flattened square and a flattened round. Adaptive launchers (API
// 26 and up) get the two layers and composite them under whatever mask the OEM uses.
const DENSITIES = [
  {dir: 'mipmap-mdpi', legacy: 48, adaptive: 108},
  {dir: 'mipmap-hdpi', legacy: 72, adaptive: 162},
  {dir: 'mipmap-xhdpi', legacy: 96, adaptive: 216},
  {dir: 'mipmap-xxhdpi', legacy: 144, adaptive: 324},
  {dir: 'mipmap-xxxhdpi', legacy: 192, adaptive: 432},
];
const RES = join(REPO, 'android', 'app', 'src', 'main', 'res');

const written = [];
const stale = [];

// ImageMagick stamps a PNG tIME chunk, so two renders of the same SVG differ by the second they
// were made. That would make every output permanently "stale" and the --check gate permanently
// red, which is worse than no gate: a check that always fails gets ignored. Stripping metadata
// makes a render a pure function of the source, which is what lets byte equality mean freshness.
const DETERMINISTIC = ['-strip', '-define', 'png:exclude-chunk=date,time'];

function magick(args) {
  return execFileSync('magick', args, {encoding: 'buffer', maxBuffer: 1 << 28});
}

function emit(path, build) {
  mkdirSync(dirname(path), {recursive: true});
  const tmp = `${path}.tmp`;
  build(tmp);
  const next = readFileSync(tmp);
  const prev = existsSync(path) ? readFileSync(path) : null;
  // With metadata stripped a render is reproducible, so byte equality is a usable freshness test.
  // Comparing content rather than mtime means a fresh checkout does not look stale.
  if (prev != null && prev.equals(next)) {
    rmSync(tmp);
    return false;
  }
  if (CHECK) {
    rmSync(tmp);
    stale.push(path.slice(REPO.length + 1));
    return true;
  }
  writeFileSync(path, next);
  rmSync(tmp);
  written.push(`${path.slice(REPO.length + 1)} (${next.length} bytes)`);
  return true;
}

/** Flatten to opaque: an iOS app icon with alpha is rejected at submission. */
function renderIos(px, out) {
  magick([
    '-density', '1024',
    IOS_SRC,
    '-resize', `${px}x${px}`,
    '-background', '#F2A93B',
    '-alpha', 'remove',
    '-alpha', 'off',
    ...DETERMINISTIC,
    'PNG24:' + out,
  ]);
}

/** The adaptive layers keep their alpha: the launcher composites them. */
function renderLayer(src, px, out, opaque) {
  const args = ['-background', opaque ?? 'none', '-density', '1024', src, '-resize', `${px}x${px}`];
  if (opaque != null) {
    args.push('-alpha', 'remove', '-alpha', 'off');
  }
  args.push(...DETERMINISTIC, 'PNG32:' + out);
  magick(args);
}

/** Legacy launcher icon: the two layers composited, then masked for the round variant. */
function renderLegacy(px, out, round) {
  const bg = `${out}.bg.png`;
  const fg = `${out}.fg.png`;
  renderLayer(AND_BG, px, bg, null);
  renderLayer(AND_FG, px, fg, null);
  // The adaptive layers are 108dp canvases of which the launcher shows the middle 72dp. A legacy
  // icon has no mask doing that crop, so it is applied here: without it the mark renders at two
  // thirds the size every other launcher shows it at.
  const inset = Math.round((px * (108 - 72)) / 108 / 2);
  const view = px - inset * 2;
  const args = [
    bg, fg, '-flatten',
    '-crop', `${view}x${view}+${inset}+${inset}`, '+repage',
    '-resize', `${px}x${px}`,
  ];
  if (round) {
    // A circle the full width of the icon, which is what a round launcher expects to receive.
    args.push(
      '-alpha', 'set',
      '(', '+clone', '-alpha', 'transparent', '-fill', 'white',
      '-draw', `circle ${px / 2 - 0.5},${px / 2 - 0.5} ${px / 2 - 0.5},-0.5`,
      ')',
      '-compose', 'CopyOpacity', '-composite',
    );
  }
  args.push(...DETERMINISTIC, 'PNG32:' + out);
  magick(args);
  rmSync(bg);
  rmSync(fg);
}

// ---- geometry, measured rather than asserted -----------------------------------

/**
 * The two platform constraints, checked against the rendered pixels:
 *  - Android guarantees only a centred 66dp circle of the 108dp canvas is visible under every OEM
 *    mask, so every inked pixel of the foreground must sit inside it.
 *  - iOS masks with a superellipse; artwork outside it is clipped.
 * This runs on the real raster, so a source edit that pushes the mark out fails here instead of on
 * somebody's home screen.
 */
function verifyGeometry() {
  const probe = join(REPO, 'ios', 'build', '.icon-probe.png');
  mkdirSync(dirname(probe), {recursive: true});
  renderLayer(AND_FG, 432, probe, null);
  const txt = magick([probe, '-alpha', 'extract', '-threshold', '50%', 'txt:']).toString('utf8');
  rmSync(probe);

  const canvas = 432;
  const centre = canvas / 2;
  let maxRadius = 0;
  let inked = 0;
  for (const line of txt.split('\n')) {
    const m = line.match(/^(\d+),(\d+): .*?(white|#FFFFFF)/i);
    if (m == null) {
      continue;
    }
    inked += 1;
    const r = Math.hypot(Number(m[1]) + 0.5 - centre, Number(m[2]) + 0.5 - centre);
    if (r > maxRadius) {
      maxRadius = r;
    }
  }
  if (inked === 0) {
    throw new Error('the android foreground rendered no ink at all, so the rasteriser is broken');
  }
  const safeRadius = (canvas * 66) / 108 / 2;
  if (maxRadius > safeRadius) {
    throw new Error(
      `the android foreground leaves the 66dp safe circle: ink reaches ${maxRadius.toFixed(1)}px ` +
        `of a ${safeRadius.toFixed(1)}px radius. Scale the mark down in icon-android-foreground.svg.`,
    );
  }
  return {inked, maxRadius, safeRadius, canvas};
}

// ---- run ----------------------------------------------------------------------

const geometry = verifyGeometry();

const seen = new Set();
for (const slot of IOS_SLOTS) {
  if (seen.has(slot.px)) {
    continue;
  }
  seen.add(slot.px);
  emit(join(IOS_DIR, `icon-${slot.px}.png`), (out) => renderIos(slot.px, out));
}
emit(join(IOS_DIR, `icon-${IOS_MARKETING}.png`), (out) => renderIos(IOS_MARKETING, out));

const contents = {
  images: [
    ...IOS_SLOTS.map((s) => ({
      filename: `icon-${s.px}.png`,
      idiom: 'iphone',
      scale: s.scale,
      size: s.size,
    })),
    {
      filename: `icon-${IOS_MARKETING}.png`,
      idiom: 'ios-marketing',
      scale: '1x',
      size: '1024x1024',
    },
  ],
  info: {author: 'xcode', version: 1},
};
const contentsPath = join(IOS_DIR, 'Contents.json');
const contentsNext = `${JSON.stringify(contents, null, 2)}\n`;
if (readFileSync(contentsPath, 'utf8') !== contentsNext) {
  if (CHECK) {
    stale.push('ios/GritChat/Images.xcassets/AppIcon.appiconset/Contents.json');
  } else {
    writeFileSync(contentsPath, contentsNext);
    written.push('ios/GritChat/Images.xcassets/AppIcon.appiconset/Contents.json');
  }
}

for (const d of DENSITIES) {
  emit(join(RES, d.dir, 'ic_launcher.png'), (out) => renderLegacy(d.legacy, out, false));
  emit(join(RES, d.dir, 'ic_launcher_round.png'), (out) => renderLegacy(d.legacy, out, true));
  emit(join(RES, d.dir, 'ic_launcher_foreground.png'), (out) => renderLayer(AND_FG, d.adaptive, out, null));
  emit(join(RES, d.dir, 'ic_launcher_background.png'), (out) => renderLayer(AND_BG, d.adaptive, out, '#F2A93B'));
}

// The adaptive descriptors. Both names, because the manifest declares icon and roundIcon and a
// launcher that asks for the round one and finds no v26 descriptor falls back to the legacy raster.
const ADAPTIVE = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/app-icons.mjs from brand/icon. Do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
`;
for (const name of ['ic_launcher.xml', 'ic_launcher_round.xml']) {
  const p = join(RES, 'mipmap-anydpi-v26', name);
  mkdirSync(dirname(p), {recursive: true});
  const prev = existsSync(p) ? readFileSync(p, 'utf8') : null;
  if (prev !== ADAPTIVE) {
    if (CHECK) {
      stale.push(`android/app/src/main/res/mipmap-anydpi-v26/${name}`);
    } else {
      writeFileSync(p, ADAPTIVE);
      written.push(`android/app/src/main/res/mipmap-anydpi-v26/${name}`);
    }
  }
}

const sha = (f) => createHash('sha256').update(readFileSync(f)).digest('hex').slice(0, 12);
console.log('sources:');
for (const f of [IOS_SRC, AND_FG, AND_BG]) {
  console.log(`  ${f.slice(REPO.length + 1)}  ${sha(f)}`);
}
console.log(
  `geometry: android foreground ink reaches ${geometry.maxRadius.toFixed(1)}px of the ` +
    `${geometry.safeRadius.toFixed(1)}px safe radius on a ${geometry.canvas}px canvas ` +
    `(${geometry.inked} inked pixels)`,
);

if (CHECK) {
  if (stale.length > 0) {
    console.error(`\n${stale.length} icon output(s) missing or stale:`);
    for (const s of stale) {
      console.error(`  ${s}`);
    }
    console.error('\nRun: node scripts/app-icons.mjs');
    process.exit(1);
  }
  console.log('\nevery icon output matches the source');
} else {
  console.log(`\nwrote ${written.length} file(s):`);
  for (const w of written) {
    console.log(`  ${w}`);
  }
}
